# Generated by Django 5.0.2 on 2025-04-23 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_mentorprofile_category_mentorprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('file', models.FileField(blank=True, help_text='Optional: upload a digital file for download.', null=True, upload_to='digital_products/')),
                ('delivery_instructions', models.TextField(blank=True, help_text='Instructions for how the product will be delivered (e.g., email, link, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_products', to='marketplace.mentorprofile')),
            ],
        ),
    ]
